### ISSUE TITLE
Styles not applied to index.html.

### ISSUE THREAD

**Issue by EdOverflow** [bugbountyforum/XSS-Radar#26]
I currently cannot see the `options.css`' styles in `index.html`. All I see is this:

![image](https://user-images.githubusercontent.com/18099289/27137735-ede80a30-511e-11e7-80e5-de27cdd51171.png)

It should look like this:

![image](https://user-images.githubusercontent.com/18099289/27137762-052e37aa-511f-11e7-92b6-13587cc0f3ba.png)

I am assuming that this is an error on my part. 😄

**Comment by smiegles** [comment]
The findings page was the start of the actual findings page that I wanted to use but it required a lot more implementation. That said, I will try to add this page. Right now, this is the findings "script": https://github.com/bugbountyforum/XSS-Radar/blob/master/extension/src/inject/report.js

**Comment by cablej** [comment]
This looks to be fixed now.

**Comment by EdOverflow** [comment]
@cablej As far as I can tell, this has not been fixed. I am running the latest version and styles are not being applied to the "Findinds" page.
