### ISSUE TITLE
No result in the finding page

### ISSUE THREAD

**Issue by 007divyachawla** [bugbountyforum/XSS-Radar#29]
While testing the XSS Challenge page in http://prompt.ml/0 there is no finding since it contains the XSS. Could you please tell why it is not working in the vulnerable sites

**Comment by smiegles** [comment]
The challenge at http://prompt.ml/0 is a "self-XSS" and we don't detect self XSS vulnerabilities. The scanner would, for example, detect http://leettime.net/xsslab1/chalg1.php.
