### ISSUE TITLE
i want to submit some payloads.

### ISSUE THREAD

**Issue by manning23** [bugbountyforum/XSS-Radar#30]

**Comment by manning23** [comment]
and radar_project need monitor prompt and confirm

**Comment by EdOverflow** [comment]
Hi @manning23,

As far as I know, you can add payloads in `/extension/src/payloads`. [[1]]

[1]: https://github.com/bugbountyforum/XSS-Radar/tree/master/extension/src/payloads

**Comment by manning23** [comment]
frame.contentWindow.document.write(`
        <script>
            function alert(m) {
                setTimeout(function () {
                    parent.postMessage("xss_" + m, "*")
                }, 1000);
            }

            function prompt(m) {
                setTimeout(function () {
                    parent.postMessage("xss_" + m, "*")
                }, 1000);
            }

            function confirm(m) {
                setTimeout(function () {
                    parent.postMessage("xss_" + m, "*")
                }, 1000);
            }
            setTimeout(function () {
                document.querySelectorAll('a').forEach((element) => {
                    var href = element.getAttribute('href')
                    if (href && href.indexOf('javascript:') == 0) element.click()
                    var onmouseover = element.getAttribute('onmouseover')
                    if (onmouseover && onmouseover.indexOf('javascript:') == 0) element.onmouseover()
                })
            }, 1000)
        </script>` + html)


i add this code, it's work well

**Comment by cablej** [comment]
Hi @manning23,

If you would like to make changes, could you please create a pull request with your changes? That way we can review your code.

Thanks.
