### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by rakesh6927** [bugbountyforum/XSS-Radar#31]
when i click on fuzz button a new window opens and showing as findings but no popups and no xss even the site is vulnerable and i tried it manually 
![screenshot at 2017-06-15 13-29-06](https://user-images.githubusercontent.com/25160144/27171274-0184a78c-517f-11e7-9bcc-fd186097fb3e.png)

**Comment by EdOverflow** [comment]
Make sure to add some payloads to the [payloads list](https://github.com/bugbountyforum/XSS-Radar/tree/master/extension/src/payloads) and then try scanning again. 🙂

**Comment by cablej** [comment]
Hi @rakesh6927,

Could you provide the url that you're testing so I can take a look?

Thanks.

**Comment by rakesh6927** [comment]
https://cloudsupport.ruckuswireless.com/search?query=%3Cscript%3Ealert%281%29%3C%2Fscript%3E&collection=&ref=

**Comment by EdOverflow** [comment]
Works for me. XSS Radar successfully detected an XSS vulnerability.

**Comment by rakesh6927** [comment]
did u uploaded any payloads or used default ?

**Comment by EdOverflow** [comment]
I used the default list. XSS Radar returned: `https://cloudsupport.ruckuswireless.com/search?query=test<script>alert(1)</script>&collection=&ref=`

**Comment by rakesh6927** [comment]
in my case its not working

could u say the steps to do ??

**Comment by EdOverflow** [comment]
1) Make sure you have the latest version of XSS Radar;
2) Visit https://cloudsupport.ruckuswireless.com/search?query=test&collection=&ref=;
3) Click the "Fuzz" button;
4) View the "Findings" window (This may take a couple of seconds).

**Comment by rakesh6927** [comment]
yeh got now,thank you

**Comment by rakesh6927** [comment]
can i use payloads of my own ?

**Comment by cablej** [comment]
Yes @rakesh6927, you can modify the file at `extension/src/payloads/general.js` with your payloads, and then reload the extension on the Chrome extensions page.

**Comment by rakesh6927** [comment]
thank you,can u share the useful payloads link ??

**Comment by EdOverflow** [comment]
https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet
http://brutelogic.com.br/blog/cheat-sheet/
https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/blns.txt
