### ISSUE TITLE
Fuzz button cant be clicked on chromium

### ISSUE THREAD

**Issue by AjayKulal** [bugbountyforum/XSS-Radar#35]
- [ ] I have searched for duplicate or closed issues.
- [ ] Operating system and version:
- [ ] Browser version:

**Comment by EdOverflow** [comment]
Could you please check the console log?

1) Right click the XSS Radar extension icon;
2) Click on “Inpsect pop-up”;
3) Check the "Console" tab.

Also in future, could you please go through all the requirements provided by our `ISSUES_TEMPLATE.md` and describe what you did and what you expected? Console logs and screenshots can also be a great help. 😉

**Comment by AjayKulal** [comment]
Here is the screenshot
![screenshot from 2017-06-16 03 14 18](https://user-images.githubusercontent.com/6723538/27203186-4574a0be-5242-11e7-9b9d-713062983c5f.png)

**Comment by smiegles** [comment]
Hi! I pushed a fix to https://github.com/bugbountyforum/XSS-Radar/tree/olivier/strict. If you could pull this branch and see if it works, that would be great :-)

**Comment by AjayKulal** [comment]
Getting new error
![screenshot from 2017-06-16 04 19 25](https://user-images.githubusercontent.com/6723538/27204872-36d314b0-524b-11e7-9c40-c305785a5352.png)

**Comment by smiegles** [comment]
Pushed a fix (I hope).. Could you verify?

**Comment by AjayKulal** [comment]
new error
![screenshot from 2017-06-16 04 33 11](https://user-images.githubusercontent.com/6723538/27205196-0333ff78-524d-11e7-8e19-b24aa0d2b919.png)

**Comment by smiegles** [comment]
Can you check your version at chrome://settings/help for me?

**Comment by AjayKulal** [comment]
Version 43.0.2357.65 Built on 8.0, running on Debian Kali Linux 2.0 (64-bit)

**Comment by smiegles** [comment]
That's 2 years old.
