### ISSUE TITLE
 Manifest file is missing or unreadable Could not load manifest.

### ISSUE THREAD

**Issue by Wayc0des-Land** [bugbountyforum/XSS-Radar#55]
## Specifications

- [Yes ] I have searched for duplicate or closed [issues](https://github.com/bugbountyforum/XSS-Radar/issues).
- [Yes ] Operating system and version: Windows 10 Pro
- [Yes ] Browser version: Google Chrome Version 74.0.3729.131 (Official Build) (64-bit)

## Issue details
Failed to load extension
 Manifest file is missing or unreadable Could not load manifest.

![failed to load extension](https://user-images.githubusercontent.com/49187195/57190752-612a4780-6f48-11e9-881f-234e28bb2e43.jpg)

**Comment by Wayc0des-Land** [comment]
solved by me

**Comment by brownyin365** [comment]
please can you provide us with the solution
